# Generated by Django 2.2 on 2020-12-04 15:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search_shloka_sp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
            managers=[
                ('SearchShloka', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SPList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spname', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
