# Generated by Django 2.2 on 2020-12-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=1000)),
                ('ptype', models.IntegerField()),
                ('spid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr_app.SPList')),
            ],
        ),
    ]
