# Generated by Django 2.2 on 2020-12-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr_app', '0002_parameterlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterlist',
            name='spid',
            field=models.ForeignKey(db_column='spid', on_delete=django.db.models.deletion.CASCADE, to='dr_app.SPList'),
        ),
    ]
