# Generated by Django 2.2 on 2021-01-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr_app', '0003_auto_20201205_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search_shloka_sp',
        ),
        migrations.AddField(
            model_name='splist',
            name='spid',
            field=models.PositiveIntegerField(db_column='spid', default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameterlist',
            name='spid',
            field=models.ForeignKey(db_column='spid', on_delete=django.db.models.deletion.CASCADE, to='dr_app.SPList', to_field='spid'),
        ),
    ]
