# Generated by Django 2.2 on 2020-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientassociation',
            name='doctor_id',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorpatientassociation',
            name='patient_id',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
